apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application
  annotations:
    kafka.apache.org/consumer-groups: zen-cluster/https://dashboard.com
spec:

  type: service
  lifecycle: production
  owner: user:michal.skoryk_zen.com
  providesApis:
    - test-api-2
  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application-2
  tags:
    - "test1"
    - "test2"
    - "test3"
    - "test4"
    - "test5"
    - "test6"
    - "test7"
    - "test8"
    - "test9"
    - "test10"

spec:

  type: service
  lifecycle: production
  owner: user:krzysztof.tokarz_zen.com
  domain: test-domain
  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application-3
spec:

  type: service
  lifecycle: production
  owner: group:Technology_-_Development
  providesApis:
    - test-api
  domain: test-domain