apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application
spec:

  type: service
  lifecycle: production
  owner: user:michal.skoryk_zen.com
  providesApis:
    - test-api-2
  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application-2
spec:

  type: service
  lifecycle: production
  owner: user:krzysztof.tokarz_zen.com
  domain: test-domain
  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application-3
spec:

  type: service
  lifecycle: production
  owner: group:Technology_-_Development
  providesApis:
    - test-api
  domain: test-domain