apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ths-event-store
  title: THS event store
  annotations:
    kafka.apache.org/consumer-groups: zen-cluster/event-store-group-id
    jenkins.io/job-full-name-zen: g2a:zen/ths-event-processor.build
spec:
  type: service
  lifecycle: production
  owner: user:michal.skoryk_zen.com
  providesApis:
    - test-api-2
  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ths-searcher
  title: THS searcher
  tags:
    - "test1"
    - "test2"
    - "test3"
    - "test4"
    - "test5"
    - "test6"
    - "test7"
    - "test8"
    - "test9"
    - "test10"
  annotations:
    jenkins.io/job-full-name-zen: g2a:zen/ths-event-processor.build
spec:
  type: service
  lifecycle: production
  owner: user:krzysztof.tokarz_zen.com
  domain: test-domain
  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ths-event-processor
  title: THS event processor
  annotations:
    kafka.apache.org/consumer-groups: zen-cluster/ths-event-processor-group
    jenkins.io/job-full-name-zen: g2a:zen/ths-event-processor.build
spec:
  type: service
  lifecycle: production
  owner: group:Technology_-_Development
  providesApis:
    - test-api
  domain: test-domain