apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ths-event-store-test
  title: THS event store test
  tags:
    - "kafka"
  annotations:
    jenkins.io/job-full-name: g2a:FinancialServices/ths-event-store.build
spec:
  domain: test-domain
  type: service
  lifecycle: production
  owner: user:michal.skoryk_zen.com
  providesApis:
    - test-api-2
  kafka:
    topic:
      appl_name_abbriev: APG
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ths-searcher-test
  title: THS searcher test
  tags:
    - "test1"
    - "test2"
    - "test3"
    - "test4"
    - "test5"
    - "test6"
    - "test7"
    - "test8"
    - "test9"
    - "test10"
  annotations:
    jenkins.io/job-full-name: zen:FinancialServices/ths-searcher.build
spec:
  type: service
  lifecycle: production
  owner: user:krzysztof.tokarz_zen.com
  domain: test-domain
  providesApis:
    - api-name
  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ths-event-processor-test
  title: THS event processor test
  tags:
    - "kafka"
  annotations:
    jenkins.io/job-full-name: zen:FinancialServices/ths-event-processor.build
spec:
  kafka:
    consumerGroupFile: 
      $yaml: ../applicationTHS/application.prod.yml 
  type: service
  lifecycle: production
  owner: group:Technology_-_Development
  providesApis:
    - test-api
  domain: test-domain

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-name
  description: Some description of the api-name interface
  title: API TO TEST
spec:
  type: openapi
  lifecycle: production
  owner: username
  domain: test-domain
  definition: 
    $text: https://artifactory.zen.local/artifactory/docs-local/epg/bff/docs/master/page/open-api/api.yaml
  apiConsumedBy:
    $yaml: ../applicationTHS/application.prod.yml