apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application
  title: test-dictionary-double
spec:
  system: system-1-test
  type: service
  lifecycle: production
  owner: michal.skoryk_zen.com
  providesApis:
    - test-api-2
  consumesApis:
    - test-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application-2
  title: test-dictionary-double
spec:
  system: system-1-test
  type: service
  lifecycle: production
  owner: krzysztof.tokarz_zen.com
  providesApis:
    - test-api
  consumesApis:
    - test-api-2
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application-3
  title: test-dictionary-double
spec:
  system: system-1-test
  type: service
  lifecycle: production
  owner: group:Technology_-_Development
  providesApis:
    - test-api