apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application
  title: test-dictionary-double
spec:
  system: system-1-test
  type: service
  lifecycle: production
  owner: backend-team
  providesApis:
    - test-api-2
  consumesApis:
    - test-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application
  title: test-dictionary-double
spec:
  system: system-1-test
  type: service
  lifecycle: production
  owner: backend-team
  providesApis:
    - test-api
  consumesApis:
    - test-api-2
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application
  title: test-dictionary-double
spec:
  system: system-1-test
  type: service
  lifecycle: production
  owner: backend-team
  providesApis:
    - test-api