apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-dictionary-application
  title: test-dictionary-double
spec:
  system: system-1-test, system-2-test
  type: service
  lifecycle: production
  owner: backend-team
  