apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  description: |
    hi this is very important
    for me and for my friends
    so please work just fine
  name: test-api
spec:
  system: system-1-test
  type: openapi
  lifecycle: production
  owner: backend-team
  definition: 
    $text: https://docs.code.g2a.com/fs/ths_searcher/api/1.10.0-SNAPSHOT/swagger.json