apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-1-test
spec:
  owner: Technology

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-2-test
spec:
  owner: Technology

    